### ISSUE TITLE
use on mac?

### ISSUE THREAD

**Issue by agentwolf88** [MysteryDash/Offline-PS4-Remote-Play#25]
Is there a way to patch the remote play app on a mac? Its not possible to start the app on a mac without internet.

**Comment by MysteryDash** [comment]
The macOS version of the RemotePlay was made with Swift, and neither macOS nor Swift are my areas of expertise. I still checked it out and I might be able to end with something usable but since I'm probably not going to do it did you try the "Alternative method, almost 0 programming skill required" method I'm giving at the end of the readme?

**Comment by agentwolf88** [comment]
What do you mean with "I'm giving at the end of the readme?"?
Sorry i am german.

**Comment by MysteryDash** [comment]
## Alternative method, almost 0 programming skill required.

1. Download and install [Fiddler](http://www.telerik.com/fiddler).
2. [Enable HTTPS decryption in Fiddler](https://www.fiddlerbook.com/fiddler/help/httpsdecryption.asp).
3. a. With Fiddler running, start Remote Play and wait for the request to https://remoteplay.dl.playstation.net/remoteplay/module/win/rp-version-win.json.
3. b. You might also see a request to https://remoteplay.dl.playstation.net/remoteplay/module/pplist_v2.json, handle it the same way as the previous one.
4. Select the AutoResponder tab, enable the rules, enable unmatched requests passthrough.
5. Drag & Drop the request made to remoteplay.dl.playstation.net into the rules list.
6. Select the FiddlerScript tab and look for this line:
```csharp
static function OnBeforeRequest(oSession: Session) {
```
7. Add the following content under the line you found earlier :
```csharp
if (oSession.HTTPMethodIs("CONNECT"))
{
    oSession.oFlags["x-replywithtunnel"] = "GenerateTunnel";
    return;
}
```
8. Click on Save Script.
9. That's it for Fiddler. You have nothing to save by yourself. The only thing that matters now is that Fiddler must be up and running when you want to play without Internet.
10. There's still something to do. Currently, if you open Remote Play, it'll tell you that (if you are truly disconnected) there is not network connection available. To fix this, create an access point on your phone and connect to it (there's no need to have an Internet connection available on your phone, otherwise it would defeat the point of having done everything mentionned above). Note that you can also use any free hotspot you may have around you.
11. It's already done ! When you'll start the Remote Play, it'll think that an Internet connection is available (when it's merely connected to a hotspot WITHOUT Internet) and when it'll try to look for updates Fiddler will take care of it.
12. Enjoy the offline PS4 Remote Play.

**Comment by agentwolf88** [comment]
THX, i will try this.

**Comment by agentwolf88** [comment]
No way. Where can i find the requests? On the left side in fiddler? If it so, the is only one request.
https://remoteplay.dl.playstation.net/remoteplay/module/pplist_v2.json
Drag and Drop does not work.
I cant find the Fiddlerscript Tab.

**Comment by MysteryDash** [comment]
![image](https://user-images.githubusercontent.com/4283036/51079232-da650c80-16c3-11e9-98ad-2ed81ce4603a.png)

**Comment by agentwolf88** [comment]
Ok, looks like a little bit different. I test again. THX
