### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by MrOrangeTan** [MysteryDash/Offline-PS4-Remote-Play#40]
1.) What do I do after I run the auto-patcher?

2.) Do I need a jailbroken PS4 with CFW?

3.) Could this brick my PS4?

4.) Could this lock my PSN account?

5.) Is there anything else I should know as a noobie?

**Comment by e-t-l** [comment]
1) Use PS4 Remote Play as usual (note: doesn't seem to be working with recent versions, and this repo appears abandoned. I suggest rolling back to a previous version of the Remote Play app as listed in the Readme. Haven't tried it yet myself to confirm though).
2) No. This program makes changes only to the PC app. It does nothing to your PS4.
3) No. See above.
4) ...Probably not. Since the point of the patch is to keep all the communication local, I don't see how PSN would even detect you're using it. And if they did, why would they care? You're not getting anything out of them without paying, because this patcher provides a service that Sony doesn't even offer. Besides, if it did cause those sorts of problems, you bet people would be here in the Issues section complaining about it.
5) Probably not.

**Comment by MrOrangeTan** [comment]
Thanks for your response! You've cleared up all my worries about the issue.
